package main

import (
	"context"
	"fmt"

	"autoreas-bridge/internal/anime"
	"autoreas-bridge/internal/api/contracts"
)

type activityAnimeWriteService struct {
	query    contracts.AnimeQueryService
	writer   contracts.AnimeWriteService
	recorder anime.ActivityRecorder
	source   string
	now      func() int64
}

func (s activityAnimeWriteService) PatchAnime(ctx context.Context, id string, patch contracts.AnimePatch) (contracts.AnimePatchResult, error) {
	before, err := s.query.GetMobileAnime(ctx, id)
	if err != nil {
		return contracts.AnimePatchResult{}, err
	}
	result, err := s.writer.PatchAnime(ctx, id, patch)
	if err != nil {
		return contracts.AnimePatchResult{}, err
	}
	if result.Outcome != contracts.AnimePatchOutcomeApplied || s.recorder == nil {
		return result, nil
	}

	after, actionType := activityPatchOutcome(*before, patch)
	if actionType == "" {
		return result, nil
	}
	if err := s.recordPatchActivity(ctx, id, *before, after, actionType); err != nil {
		return contracts.AnimePatchResult{}, err
	}
	return result, nil
}

// activityPatchOutcome derives the activity snapshot and action for an anime patch.
func activityPatchOutcome(before contracts.MobileAnime, patch contracts.AnimePatch) (anime.ActivityAnimeSnapshot, string) {
	after := anime.ActivityAnimeSnapshot{Estado: before.Estado, NroCapVisto: before.NroCapVisto, Activo: before.Activo}
	actionType := ""
	if patch.Estado != nil {
		after.Estado, actionType = *patch.Estado, anime.ActivityActionAnimeStateSet
	}
	if patch.NroCapVisto != nil {
		after.NroCapVisto, actionType = *patch.NroCapVisto, anime.ActivityActionChapterAdjusted
	}
	if patch.Activo != nil {
		after.Activo = 0
		actionType = anime.ActivityActionAnimeSoftDeleted
		if *patch.Activo {
			after.Activo, actionType = 1, anime.ActivityActionAnimeRestored
		}
	}
	if patch.RepeatAt != nil {
		return anime.ActivityAnimeSnapshot{Estado: 0, NroCapVisto: 0, Activo: 1}, anime.ActivityActionAnimeRepeated
	}
	return after, actionType
}

// recordPatchActivity persists the activity generated by a successful anime patch.
func (s activityAnimeWriteService) recordPatchActivity(ctx context.Context, id string, before contracts.MobileAnime, after anime.ActivityAnimeSnapshot, actionType string) error {
	now := s.now
	if now == nil {
		now = func() int64 { return 0 }
	}
	occurredAtMs := now()
	source := s.source
	if source == "" {
		source = anime.ActivitySourceSystem
	}
	return s.recorder.RecordActivity(ctx, anime.ActivityRecord{
		Source:        source,
		ActionType:    actionType,
		AnimeID:       id,
		AnimeName:     before.Nombre,
		OccurredAtMs:  occurredAtMs,
		CorrelationID: fmt.Sprintf("anime.patch:%s:%d", id, occurredAtMs),
		Before: anime.ActivityAnimeSnapshot{
			Estado:      before.Estado,
			NroCapVisto: before.NroCapVisto,
			Activo:      before.Activo,
		},
		After: after,
	})
}
