package main

import (
	"path/filepath"
	"strings"
	"testing"
)

var broadLegacyPathExemptionCases = []struct {
	name    string
	path    string
	content string
}{
	{
		name: "arbitrary file in Legacy package",
		path: "internal/anime/legacy/parallel_reader.go",
		content: `package legacy
import "os"
func parallelRead() { _, _ = os.ReadFile("animes.dat") }
`,
	},
	{
		name: "parallel domain raw file",
		path: "internal/anime/domain/anime_raw_parallel.go",
		content: "package domain\n" +
			"import \"encoding/json\"\n" +
			"type raw struct {\n" +
			"  Page string `json:\"pagina\"`\n" +
			"  Progress float64 `json:\"nrocapvisto\"`\n" +
			"}\n" +
			"func encode(value raw) { _, _ = json.Marshal(value) }\n",
	},
	{
		name: "existing parallel domain DTO path",
		path: "internal/anime/domain/anime_raw.go",
		content: "package domain\n" +
			"import \"encoding/json\"\n" +
			"type LegacyAnimeRaw struct {\n" +
			"  Pagina string `json:\"pagina\"`\n" +
			"  Activo bool `json:\"activo\"`\n" +
			"}\n" +
			"func (value LegacyAnimeRaw) MarshalJSON() ([]byte, error) { return json.Marshal(value) }\n",
	},
	{
		name: "snapshot raw DTO support leak",
		path: "internal/anime/snapshot.go",
		content: `package anime
import boundary "autoreas-bridge/internal/anime/legacy"
func normalize(raw boundary.LegacyAnimeRaw) { _ = raw.Pagina }
`,
	},
	{
		name: "application imports parallel domain DTO",
		path: "internal/season/domain_raw.go",
		content: `package season
import (
  "encoding/json"
  "autoreas-bridge/internal/anime/domain"
)
func decode(payload []byte) {
  var raw domain.LegacyAnimeRaw
  _ = json.Unmarshal(payload, &raw)
}
`,
	},
}

func TestRunRejectsFilesHiddenByBroadLegacyPathExemptions(t *testing.T) {
	t.Parallel()
	for _, tt := range broadLegacyPathExemptionCases {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writeFile(t, root, tt.path, tt.content)
			if err := run(root); err == nil {
				t.Fatal("expected parallel Legacy boundary violation")
			}
		})
	}
}

func TestRunAllowsOnlyExactLegacyBoundaryImplementationFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/anime/legacy/wire.go", "package legacy\n"+
		"import \"encoding/json\"\n"+
		"type LegacyAnimeRaw struct {\n"+
		"  Pagina string `json:\"pagina\"`\n"+
		"  Activo bool `json:\"activo\"`\n"+
		"}\n"+
		"func encode(value LegacyAnimeRaw) { _, _ = json.Marshal(value) }\n")
	writeFile(t, root, "internal/anime/legacy/gateway.go", `package legacy
import "os"
func load() { _, _ = os.ReadFile("animes.dat") }
`)

	if err := run(root); err != nil {
		t.Fatalf("expected exact Legacy implementation files to pass, got %v", err)
	}
}

func TestRunRequiresCanonicalGeneratedHeaderBeforePackage(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		content   string
		wantError bool
	}{
		{
			name: "canonical leading header",
			content: `// Code generated by fixture. DO NOT EDIT.
package season
import "os"
func read() { _, _ = os.ReadFile("animes.dat") }
`,
		},
		{
			name: "marker text inside string",
			content: `package season
import "os"
const generated = "Code generated"
const edit = "DO NOT EDIT"
func read() { _, _ = os.ReadFile("animes.dat") }
`,
			wantError: true,
		},
		{
			name: "canonical text after package",
			content: `package season
// Code generated by fixture. DO NOT EDIT.
import "os"
func read() { _, _ = os.ReadFile("animes.dat") }
`,
			wantError: true,
		},
		{
			name: "noncanonical leading comment",
			content: `// Code generated by fixture; DO NOT EDIT
package season
import "os"
func read() { _, _ = os.ReadFile("animes.dat") }
`,
			wantError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writeFile(t, root, "internal/season/generated_policy.go", tt.content)
			err := run(root)
			if tt.wantError && err == nil {
				t.Fatal("expected generated-header policy violation")
			}
			if !tt.wantError && err != nil {
				t.Fatalf("expected canonical generated file to pass, got %v", err)
			}
		})
	}
}

func TestRunReturnsDeterministicMultipleLegacyDiagnostics(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/season/multiple.go", "package season\n"+
		"import (\"encoding/json\"; \"os\")\n"+
		"type wireRecord struct {\n"+
		"  Page string `json:\"pagina\"`\n"+
		"  Progress float64 `json:\"nrocapvisto\"`\n"+
		"}\n"+
		"func violate(value wireRecord) {\n"+
		"  _, _ = os.ReadFile(\"animes.dat\")\n"+
		"  _, _ = json.Marshal(value)\n"+
		"}\n")

	want := "architecture violations:\n" +
		"- internal/season/multiple.go:8 performs animes.dat file I/O outside the Legacy gateway\n" +
		"- internal/season/multiple.go:9 serializes Legacy JSON outside the Legacy adapter"
	for runNumber := 0; runNumber < 20; runNumber++ {
		err := run(root)
		if err == nil {
			t.Fatal("expected multiple architecture violations")
		}
		if got := filepath.ToSlash(err.Error()); got != want {
			t.Fatalf("run %d diagnostic mismatch\nwant:\n%s\ngot:\n%s", runNumber, want, got)
		}
	}
}

func TestRunAllowsDocumentationAndRuntimeSpanishValues(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/season/runtime_values.go", `package season
// animes.dat remains the external source; this comment performs no I/O.
const documentation = "animes.dat"
const unseenSection = "Sin ver"
const watchTodaySection = "Ver hoy"
`)

	if err := run(root); err != nil {
		message := filepath.ToSlash(err.Error())
		if strings.Contains(message, "Legacy") || strings.Contains(message, "animes.dat") {
			t.Fatalf("expected comments and runtime Spanish values to pass, got %v", err)
		}
	}
}
