package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestRunRejectsActivityLogReferencesOutsideActivityContext(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/anime/service.go", `package anime
const query = "INSERT INTO activity_log DEFAULT VALUES"
`)

	err := run(root)
	if err == nil {
		t.Fatal("expected architecture violation")
	}
}

func TestRunAllowsActivityLogReferencesInsideActivityContext(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/activity/sqlite_store.go", `package activity
const query = "INSERT INTO activity_log DEFAULT VALUES"
`)

	if err := run(root); err != nil {
		t.Fatalf("expected activity context reference to pass, got %v", err)
	}
}

func TestRunAllowsActivityLogSchemaReferencesInSQLiteBootstrap(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/sync/sqlite_bootstrap.go", `package sync
const ddl = "CREATE TABLE activity_log (id INTEGER PRIMARY KEY)"
`)

	if err := run(root); err != nil {
		t.Fatalf("expected bootstrap schema reference to pass, got %v", err)
	}
}

// TestRunHasNoLegacyBoundaryCheck proves the legacy-boundary check is fully
// retired: no source file in this package declares checkLegacyBoundary, and a
// file that would have violated the old legacy-DTO/JSON-key/animes.dat rules
// passes cleanly through run() (SDD-55 Slice D).
func TestRunHasNoLegacyBoundaryCheck(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/season/legacy_projection.go", `package season
import wire "autoreas-bridge/internal/anime/store"
func project(raw wire.LegacyAnimeRaw) string { return raw.Pagina }
`)

	if err := run(root); err != nil {
		t.Fatalf("expected legacy_boundary to be retired (no violation), got %v", err)
	}
}

func TestRunAllowsGeneratedFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "frontend/wailsjs/go/generated.go", `// Code generated by test. DO NOT EDIT.
package generated
import "os"
func readSettings() { _, _ = os.ReadFile("settings.json") }
`)

	if err := run(root); err != nil {
		t.Fatalf("expected generated file to pass, got %v", err)
	}
}

// writeFile creates a source fixture beneath a temporary root.
func writeFile(t *testing.T, root string, name string, content string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
}
