package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunRejectsActivityLogReferencesOutsideActivityContext(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/anime/service.go", `package anime
const query = "INSERT INTO activity_log DEFAULT VALUES"
`)

	err := run(root)
	if err == nil {
		t.Fatal("expected architecture violation")
	}
}

func TestRunAllowsActivityLogReferencesInsideActivityContext(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/activity/sqlite_store.go", `package activity
const query = "INSERT INTO activity_log DEFAULT VALUES"
`)

	if err := run(root); err != nil {
		t.Fatalf("expected activity context reference to pass, got %v", err)
	}
}

func TestRunAllowsActivityLogSchemaReferencesInSQLiteBootstrap(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/sync/sqlite_bootstrap.go", `package sync
const ddl = "CREATE TABLE activity_log (id INTEGER PRIMARY KEY)"
`)

	if err := run(root); err != nil {
		t.Fatalf("expected bootstrap schema reference to pass, got %v", err)
	}
}

var legacyGatewayBoundaryViolationCases = []struct {
	name     string
	path     string
	content  string
	expected string
}{
	{
		name: "qualified Legacy DTO alias",
		path: "internal/season/legacy_projection.go",
		content: `package season
import wire "autoreas-bridge/internal/anime/legacy"
func project(raw wire.LegacyAnimeRaw) string { return raw.Pagina }
`,
		expected: "internal/season/legacy_projection.go:3 uses legacy.LegacyAnimeRaw outside the Legacy adapter",
	},
	{
		name: "inferred Spanish Legacy wire field",
		path: "internal/season/legacy_decoder.go",
		content: `package season
import wire "autoreas-bridge/internal/anime/legacy"
func page(payload []byte) string {
  raw, _, _, _ := wire.Decode(payload)
  return raw.Pagina
}
`,
		expected: "internal/season/legacy_decoder.go:5 uses Spanish Legacy wire field Pagina outside the Legacy adapter",
	},
	{
		name: "aliased animes.dat file read",
		path: "internal/season/parallel_reader.go",
		content: `package season
import filesystem "os"
const animeDataPath = "data/animes.dat"
func read() { _, _ = filesystem.ReadFile(animeDataPath) }
`,
		expected: "internal/season/parallel_reader.go:4 performs animes.dat file I/O outside the Legacy gateway",
	},
	{
		name: "parallel Legacy JSON serializer",
		path: "internal/season/legacy_encoder.go",
		content: "package season\n" +
			"import codec \"encoding/json\"\n" +
			"type legacyEnvelope struct {\n" +
			"  Page string `json:\"pagina\"`\n" +
			"  Progress float64 `json:\"nrocapvisto\"`\n" +
			"  Active bool `json:\"activo\"`\n" +
			"}\n" +
			"func encode(value legacyEnvelope) { _, _ = codec.Marshal(value) }\n",
		expected: "internal/season/legacy_encoder.go:8 serializes Legacy JSON outside the Legacy adapter",
	},
}

func TestRunRejectsLegacyGatewayBoundaryViolations(t *testing.T) {
	t.Parallel()
	for _, tt := range legacyGatewayBoundaryViolationCases {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			writeFile(t, root, tt.path, tt.content)

			err := run(root)
			if err == nil {
				t.Fatal("expected Legacy boundary violation")
			}
			if !strings.Contains(filepath.ToSlash(err.Error()), tt.expected) {
				t.Fatalf("expected actionable violation %q, got %v", tt.expected, err)
			}
		})
	}
}

func TestRunAllowsNonLegacyAndApprovedGatewayFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFile(t, root, "internal/season/english_contract.go", `package season
import "os"
type Anime struct { SourceURL string }
const documentation = "animes.dat is the Legacy source"
const runtimeSection = "Sin ver"
func readSettings() { _, _ = os.ReadFile("settings.json") }
`)
	writeFile(t, root, "internal/anime/legacy/gateway.go", `package legacy
import "os"
func load() { _, _ = os.ReadFile("animes.dat") }
`)
	writeFile(t, root, "internal/season/ignored_test.go", `package season
import "os"
func parallelRead() { _, _ = os.ReadFile("animes.dat") }
`)
	writeFile(t, root, "frontend/wailsjs/go/generated.go", `// Code generated by test. DO NOT EDIT.
package generated
import "os"
func parallelRead() { _, _ = os.ReadFile("animes.dat") }
`)

	if err := run(root); err != nil {
		t.Fatalf("expected non-Legacy and approved gateway files to pass, got %v", err)
	}
}

// writeFile creates a source fixture beneath a temporary root.
func writeFile(t *testing.T, root string, name string, content string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
}
