package desktop

import (
	"context"
	"fmt"

	"autoreas-bridge/internal/activity"
	"autoreas-bridge/internal/anime"
	"autoreas-bridge/internal/api/contracts"
	sharedlogger "autoreas-bridge/internal/logger"
	"autoreas-bridge/internal/watchhistory"
)

type activityAnimeWriteService struct {
	query         contracts.AnimeQueryService
	writer        contracts.AnimePatcher
	recorder      anime.ActivityRecorder
	watchRecorder anime.WatchRecorder
	logger        sharedlogger.Logger
	source        string
	now           func() int64
}

func (s activityAnimeWriteService) PatchAnime(ctx context.Context, id string, patch contracts.AnimePatch) (contracts.AnimePatchResult, error) {
	before, err := s.query.GetMobileAnime(ctx, id)
	if err != nil {
		return contracts.AnimePatchResult{}, err
	}
	result, err := s.writer.PatchAnime(ctx, id, patch)
	if err != nil {
		return contracts.AnimePatchResult{}, err
	}
	if result.Outcome != contracts.AnimePatchOutcomeApplied {
		return result, nil
	}

	occurredAtMs := s.occurredAtMs()
	if s.recorder != nil {
		after, actionType := activityPatchOutcome(*before, patch)
		if actionType != "" {
			if err := s.recordPatchActivity(ctx, id, *before, after, actionType, occurredAtMs, reportedAtMs(patch.FechaUltCapVisto)); err != nil {
				return contracts.AnimePatchResult{}, err
			}
		}
	}
	s.recordWatch(ctx, id, *before, patch, occurredAtMs)
	return result, nil
}

// occurredAtMs returns the current time in epoch milliseconds, defaulting to
// zero when no clock was wired.
func (s activityAnimeWriteService) occurredAtMs() int64 {
	if s.now == nil {
		return 0
	}
	return s.now()
}

// activitySource returns the configured activity source, defaulting to
// system when none was wired.
func (s activityAnimeWriteService) activitySource() string {
	if s.source == "" {
		return anime.ActivitySourceSystem
	}
	return s.source
}

// recordWatch computes the real watch-history change straight from the
// before/after episode diff -- never activityPatchOutcome's derived
// actionType, which collapses to a single action label for a patch that
// might touch several fields at once (design.md D4, task-planning note
// 2.2.3) -- and delegates the record-or-degrade guard to anime.RecordWatch,
// which both live write paths share.
func (s activityAnimeWriteService) recordWatch(ctx context.Context, id string, before contracts.MobileAnime, patch contracts.AnimePatch, occurredAtMs int64) {
	after := before.EpisodesWatched
	if patch.NroCapVisto != nil {
		after = *patch.NroCapVisto
	}
	anime.RecordWatch(ctx, s.watchRecorder, s.logger, id, watchhistory.Change{
		AnimeID:        id,
		AnimeName:      before.Name,
		Source:         s.activitySource(),
		OccurredAtMS:   occurredAtMs,
		ReportedAtMS:   reportedAtMs(patch.FechaUltCapVisto),
		BeforeEpisodes: before.EpisodesWatched,
		AfterEpisodes:  after,
		Cycle:          int64(len(before.Repetitions)) + 1,
		CycleReset:     patch.RepeatAt != nil,
	})
}

// reportedAtMs returns the instant the source reported for a patch, or 0 when
// the patch reported none. The watch-time projection treats 0 as "not
// reported" and falls back to the receipt instant (design.md D1), so a patch
// that carries no report must not be given a synthetic one here.
func reportedAtMs(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}

// activityPatchOutcome derives the activity snapshot and action for an anime patch.
func activityPatchOutcome(before contracts.MobileAnime, patch contracts.AnimePatch) (anime.ActivityAnimeSnapshot, string) {
	after := anime.ActivityAnimeSnapshot{Estado: before.Status, NroCapVisto: before.EpisodesWatched, Activo: before.Active}
	actionType := ""
	if patch.Estado != nil {
		after.Estado, actionType = *patch.Estado, anime.ActivityActionAnimeStateSet
	}
	if patch.NroCapVisto != nil {
		after.NroCapVisto, actionType = *patch.NroCapVisto, activity.ActionEpisodeAdjusted
	}
	if patch.Activo != nil {
		after.Activo = 0
		actionType = anime.ActivityActionAnimeSoftDeleted
		if *patch.Activo {
			after.Activo, actionType = 1, anime.ActivityActionAnimeRestored
		}
	}
	if patch.RepeatAt != nil {
		return anime.ActivityAnimeSnapshot{Estado: 0, NroCapVisto: 0, Activo: 1}, anime.ActivityActionAnimeRepeated
	}
	return after, actionType
}

// recordPatchActivity persists the activity generated by a successful anime patch.
// occurredAtMs stays the instant the bridge observed the change -- that is what
// this row audits -- while the patch's own reported instant is retained
// alongside it so the replay can reproduce the same projection (design.md D4).
func (s activityAnimeWriteService) recordPatchActivity(ctx context.Context, id string, before contracts.MobileAnime, after anime.ActivityAnimeSnapshot, actionType string, occurredAtMs, reportedAtMS int64) error {
	return s.recorder.RecordActivity(ctx, anime.ActivityRecord{
		Source:        s.activitySource(),
		ActionType:    actionType,
		AnimeID:       id,
		AnimeName:     before.Name,
		OccurredAtMs:  occurredAtMs,
		CorrelationID: fmt.Sprintf("anime.patch:%s:%d", id, occurredAtMs),
		ReportedAtMS:  reportedAtMS,
		Before: anime.ActivityAnimeSnapshot{
			Estado:      before.Status,
			NroCapVisto: before.EpisodesWatched,
			Activo:      before.Active,
		},
		After: after,
	})
}
