// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {logger} from '../models';
import {main} from '../models';

export function AdjustWatchedChapters(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function CloseSeason():Promise<string>;

export function CopyAnimeFolder(arg1:string):Promise<contracts.ChapterCommandResult>;

export function CopyAnimePage(arg1:string):Promise<contracts.ChapterCommandResult>;

export function CreateSeason(arg1:string):Promise<string>;

export function DiscardSeasonName(arg1:string):Promise<string>;

export function GetAnimeCover(arg1:string):Promise<contracts.AnimeCover>;

export function GetAnimeDetail(arg1:string):Promise<contracts.MobileAnime>;

export function GetAnimeDetailView(arg1:string):Promise<contracts.AnimeDetail>;

export function GetAnimeHistory():Promise<Array<contracts.AnimeHistoryItem>>;

export function GetAnimes():Promise<Array<contracts.AnimeListItem>>;

export function GetBridgeStatus():Promise<string>;

export function GetChapterDayCounts():Promise<Array<contracts.ChapterDayCount>>;

export function GetChapterSchedule(arg1:string):Promise<Array<contracts.ChapterScheduleItem>>;

export function GetConnectedDevices():Promise<Array<contracts.DeviceInfo>>;

export function GetDownloadConfig():Promise<contracts.DownloadConfig>;

export function GetEffectiveAddress():Promise<string>;

export function GetJDStatus():Promise<contracts.JDStatus>;

export function GetPairingToken():Promise<string>;

export function GetRecentLogs():Promise<Array<logger.LogEntry>>;

export function GetSQLiteStatus():Promise<string>;

export function GetScheduleConfig():Promise<contracts.ScheduleConfig>;

export function GetSeason():Promise<main.SeasonDTO>;

export function GetSeasonAnimes():Promise<Array<main.SeasonAnimeDTO>>;

export function GetSeasonMode():Promise<boolean>;

export function GetSyncingAnimeItems():Promise<Array<contracts.SyncingAnimeItem>>;

export function ImportSeasonIntake(arg1:string):Promise<string>;

export function ListDownloadRuns():Promise<Array<contracts.DownloadRunView>>;

export function OpenAnimeFolder(arg1:string):Promise<contracts.ChapterCommandResult>;

export function OpenAnimePage(arg1:string):Promise<contracts.ChapterCommandResult>;

export function PullAnimesFromLegacy():Promise<contracts.AnimeLegacyPullResult>;

export function RecheckSeasonAvailability():Promise<string>;

export function RepeatAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function ResolveSeasonMatch(arg1:string,arg2:string):Promise<string>;

export function RestoreAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function RunSeasonMatching():Promise<string>;

export function SetAnimeState(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function SetHosterPriority(arg1:string,arg2:Array<contracts.HosterPriorityItem>):Promise<string>;

export function SetJDConfig(arg1:contracts.JDConfigInput):Promise<string>;

export function SetScheduleConfig(arg1:contracts.ScheduleConfig):Promise<string>;

export function SetSeasonMinApprovalGrade(arg1:number):Promise<string>;

export function SetSeasonSlots(arg1:number):Promise<string>;

export function SoftDeleteAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function TriggerDownloadCheck():Promise<string>;

export function TriggerReconcile():Promise<string>;

export function UnpairDevice(arg1:string):Promise<string>;
