// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnimes() {
  return window['go']['main']['App']['GetAnimes']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function GetEffectiveAddress() {
  return window['go']['main']['App']['GetEffectiveAddress']();
}

export function GetPairingToken() {
  return window['go']['main']['App']['GetPairingToken']();
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetSQLiteStatus() {
  return window['go']['main']['App']['GetSQLiteStatus']();
}

export function GetSyncingAnimeItems() {
  return window['go']['main']['App']['GetSyncingAnimeItems']();
}

export function TriggerReconcile() {
  return window['go']['main']['App']['TriggerReconcile']();
}
