// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {logger} from '../models';

export function GetAnimes():Promise<Array<contracts.AnimeListItem>>;

export function AdjustWatchedChapters(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function GetBridgeStatus():Promise<string>;

export function GetChapterSchedule(arg1:string):Promise<Array<contracts.ChapterScheduleItem>>;

export function GetConnectedDevices():Promise<Array<contracts.DeviceInfo>>;

export function GetDownloadConfig():Promise<contracts.DownloadConfig>;

export function GetEffectiveAddress():Promise<string>;

export function GetJDStatus():Promise<contracts.JDStatus>;

export function GetPairingToken():Promise<string>;

export function GetRecentLogs():Promise<Array<logger.LogEntry>>;

export function GetSQLiteStatus():Promise<string>;

export function GetScheduleConfig():Promise<contracts.ScheduleConfig>;

export function GetSeasonMode():Promise<boolean>;

export function GetSyncingAnimeItems():Promise<Array<contracts.SyncingAnimeItem>>;

export function ListDownloadRuns():Promise<Array<contracts.DownloadRunView>>;

export function PullAnimesFromLegacy():Promise<contracts.AnimeLegacyPullResult>;

export function SetHosterPriority(arg1:string,arg2:Array<contracts.HosterPriorityItem>):Promise<string>;

export function SetJDConfig(arg1:contracts.JDConfigInput):Promise<string>;

export function SetAnimeState(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function SetScheduleConfig(arg1:contracts.ScheduleConfig):Promise<string>;

export function SetSeasonMode(arg1:boolean):Promise<string>;

export function TriggerDownloadCheck():Promise<string>;

export function TriggerReconcile():Promise<string>;

export function UnpairDevice(arg1:string):Promise<string>;
