// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnimes() {
  return window['go']['main']['App']['GetAnimes']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function GetDownloadConfig() {
  return window['go']['main']['App']['GetDownloadConfig']();
}

export function GetEffectiveAddress() {
  return window['go']['main']['App']['GetEffectiveAddress']();
}

export function GetJDStatus() {
  return window['go']['main']['App']['GetJDStatus']();
}

export function GetPairingToken() {
  return window['go']['main']['App']['GetPairingToken']();
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetSQLiteStatus() {
  return window['go']['main']['App']['GetSQLiteStatus']();
}

export function GetScheduleConfig() {
  return window['go']['main']['App']['GetScheduleConfig']();
}

export function GetSyncingAnimeItems() {
  return window['go']['main']['App']['GetSyncingAnimeItems']();
}

export function ListDownloadRuns() {
  return window['go']['main']['App']['ListDownloadRuns']();
}

export function SetHosterPriority(arg1, arg2) {
  return window['go']['main']['App']['SetHosterPriority'](arg1, arg2);
}

export function SetJDConfig(arg1) {
  return window['go']['main']['App']['SetJDConfig'](arg1);
}

export function SetScheduleConfig(arg1) {
  return window['go']['main']['App']['SetScheduleConfig'](arg1);
}

export function TriggerDownloadCheck() {
  return window['go']['main']['App']['TriggerDownloadCheck']();
}

export function TriggerReconcile() {
  return window['go']['main']['App']['TriggerReconcile']();
}
