// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {main} from '../models';
import {logger} from '../models';

export function AdjustWatchedChapters(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function ApplyAnimeEditorSchedule(arg1:main.ApplyAnimeScheduleDraftCommandDTO):Promise<contracts.AnimeEditorScheduleApplyResult>;

export function ApplySeasonSchedule():Promise<main.ApplyScheduleDTO>;

export function CloseSeason():Promise<string>;

export function ConfirmSeasonSelection():Promise<main.ConfirmSelectionDTO>;

export function CopyAnimeFolder(arg1:string):Promise<contracts.ChapterCommandResult>;

export function CopyAnimePage(arg1:string):Promise<contracts.ChapterCommandResult>;

export function CreateSeason(arg1:string):Promise<string>;

export function CreateSeasonAnimes(arg1:Array<string>,arg2:Record<string, string>):Promise<string>;

export function DeactivateAnime(arg1:string,arg2:number):Promise<contracts.AnimeEditorSaveResult>;

export function DiscardSeasonName(arg1:string):Promise<string>;

export function GetAnimeCover(arg1:string):Promise<contracts.AnimeCover>;

export function GetAnimeDetail(arg1:string):Promise<contracts.MobileAnime>;

export function GetAnimeDetailView(arg1:string):Promise<contracts.AnimeDetail>;

export function GetAnimeEditorRecord(arg1:string):Promise<contracts.AnimeEditorRecordResult>;

export function GetAnimeEditorScheduleBoard(arg1:string):Promise<contracts.AnimeEditorScheduleBoardResult>;

export function GetAnimeHistory():Promise<Array<contracts.AnimeHistoryItem>>;

export function GetAnimes():Promise<Array<contracts.AnimeListItem>>;

export function GetBridgeStatus():Promise<string>;

export function GetChapterDayCounts():Promise<Array<contracts.ChapterDayCount>>;

export function GetChapterSchedule(arg1:string):Promise<Array<contracts.ChapterScheduleItem>>;

export function GetConnectedDevices():Promise<Array<contracts.DeviceInfo>>;

export function GetDownloadConfig():Promise<contracts.DownloadConfig>;

export function GetDownloadsRoot():Promise<string>;

export function GetEffectiveAddress():Promise<string>;

export function GetJDStatus():Promise<contracts.JDStatus>;

export function GetPairingToken():Promise<string>;

export function GetPastSeason(arg1:string):Promise<main.SeasonDTO>;

export function GetPastSeasonAnimes(arg1:string):Promise<Array<main.SeasonAnimeDTO>>;

export function GetRecentLogs():Promise<Array<logger.LogEntry>>;

export function GetSQLiteStatus():Promise<string>;

export function GetScheduleConfig():Promise<contracts.ScheduleConfig>;

export function GetSeason():Promise<main.SeasonDTO>;

export function GetSeasonAnimes():Promise<Array<main.SeasonAnimeDTO>>;

export function GetSeasonMode():Promise<boolean>;

export function GetSeasonOrderingBoard():Promise<main.OrderingBoardDTO>;

export function GetSyncingAnimeItems():Promise<Array<contracts.SyncingAnimeItem>>;

export function ImportSeasonIntake(arg1:string):Promise<string>;

export function ListDownloadRuns():Promise<Array<contracts.DownloadRunView>>;

export function ListSeasons():Promise<Array<main.SeasonDTO>>;

export function OpenAnimeFolder(arg1:string):Promise<contracts.ChapterCommandResult>;

export function OpenAnimePage(arg1:string):Promise<contracts.ChapterCommandResult>;

export function PickFile(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function PullAnimesFromLegacy():Promise<contracts.AnimeLegacyPullResult>;

export function RecheckSeasonAvailability():Promise<string>;

export function ReconcileSeasonIntake(arg1:string):Promise<string>;

export function ReopenSeasonOrdering():Promise<string>;

export function RepeatAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function ResolveSeasonMatch(arg1:string,arg2:string):Promise<string>;

export function RestoreAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function RunSeasonMatching():Promise<string>;

export function SaveAnimeEditor(arg1:main.SaveAnimeEditorCommandDTO):Promise<contracts.AnimeEditorSaveResult>;

export function SaveSeasonOrderingDraft(arg1:string):Promise<string>;

export function SendSeasonAnimesToVerHoy(arg1:Array<string>):Promise<main.SendToVerHoyDTO>;

export function SetAnimeDays(arg1:string,arg2:Array<string>,arg3:number):Promise<contracts.ChapterCommandResult>;

export function SetAnimeState(arg1:string,arg2:number,arg3:number):Promise<contracts.ChapterCommandResult>;

export function SetDownloadsRoot(arg1:string):Promise<string>;

export function SetHosterPriority(arg1:string,arg2:Array<contracts.HosterPriorityItem>):Promise<string>;

export function SetJDConfig(arg1:contracts.JDConfigInput):Promise<string>;

export function SetScheduleConfig(arg1:contracts.ScheduleConfig):Promise<string>;

export function SetSeasonConsideration(arg1:string,arg2:string):Promise<string>;

export function SetSeasonGrade(arg1:string,arg2:number):Promise<string>;

export function SetSeasonMinApprovalGrade(arg1:number):Promise<string>;

export function SetSeasonSlots(arg1:number):Promise<string>;

export function SkipSeasonGrading(arg1:string):Promise<string>;

export function SoftDeleteAnime(arg1:string,arg2:number):Promise<contracts.ChapterCommandResult>;

export function TriggerAnimeDownload(arg1:string):Promise<string>;

export function TriggerDownloadCheck():Promise<string>;

export function TriggerReconcile():Promise<string>;

export function TriggerSeasonDownloads():Promise<string>;

export function UnpairDevice(arg1:string):Promise<string>;
