// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustWatchedEpisodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdjustWatchedEpisodes'](arg1, arg2, arg3);
}

export function ApplyAnimeEditorSchedule(arg1) {
  return window['go']['main']['App']['ApplyAnimeEditorSchedule'](arg1);
}

export function ApplySeasonSchedule() {
  return window['go']['main']['App']['ApplySeasonSchedule']();
}

export function CloseSeason() {
  return window['go']['main']['App']['CloseSeason']();
}

export function ConfirmSeasonSelection() {
  return window['go']['main']['App']['ConfirmSeasonSelection']();
}

export function CopyAnimeFolder(arg1) {
  return window['go']['main']['App']['CopyAnimeFolder'](arg1);
}

export function CopyAnimePage(arg1) {
  return window['go']['main']['App']['CopyAnimePage'](arg1);
}

export function CreateAnime(arg1) {
  return window['go']['main']['App']['CreateAnime'](arg1);
}

export function CreateSeason(arg1) {
  return window['go']['main']['App']['CreateSeason'](arg1);
}

export function CreateSeasonAnimes(arg1, arg2) {
  return window['go']['main']['App']['CreateSeasonAnimes'](arg1, arg2);
}

export function DeactivateAnime(arg1, arg2) {
  return window['go']['main']['App']['DeactivateAnime'](arg1, arg2);
}

export function DiscardSeasonName(arg1) {
  return window['go']['main']['App']['DiscardSeasonName'](arg1);
}

export function GetAnimeCover(arg1) {
  return window['go']['main']['App']['GetAnimeCover'](arg1);
}

export function GetAnimeDetail(arg1) {
  return window['go']['main']['App']['GetAnimeDetail'](arg1);
}

export function GetAnimeDetailView(arg1) {
  return window['go']['main']['App']['GetAnimeDetailView'](arg1);
}

export function GetAnimeEditorRecord(arg1) {
  return window['go']['main']['App']['GetAnimeEditorRecord'](arg1);
}

export function GetAnimeEditorScheduleBoard(arg1) {
  return window['go']['main']['App']['GetAnimeEditorScheduleBoard'](arg1);
}

export function GetAnimeHistory() {
  return window['go']['main']['App']['GetAnimeHistory']();
}

export function GetAnimes() {
  return window['go']['main']['App']['GetAnimes']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function GetConnectedDevices() {
  return window['go']['main']['App']['GetConnectedDevices']();
}

export function GetDownloadConfig() {
  return window['go']['main']['App']['GetDownloadConfig']();
}

export function GetDownloadsRoot() {
  return window['go']['main']['App']['GetDownloadsRoot']();
}

export function GetEffectiveAddress() {
  return window['go']['main']['App']['GetEffectiveAddress']();
}

export function GetEpisodeDayCounts() {
  return window['go']['main']['App']['GetEpisodeDayCounts']();
}

export function GetEpisodeSchedule(arg1) {
  return window['go']['main']['App']['GetEpisodeSchedule'](arg1);
}

export function GetJDStatus() {
  return window['go']['main']['App']['GetJDStatus']();
}

export function GetPairingToken() {
  return window['go']['main']['App']['GetPairingToken']();
}

export function GetPastSeason(arg1) {
  return window['go']['main']['App']['GetPastSeason'](arg1);
}

export function GetPastSeasonAnimes(arg1) {
  return window['go']['main']['App']['GetPastSeasonAnimes'](arg1);
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetSQLiteStatus() {
  return window['go']['main']['App']['GetSQLiteStatus']();
}

export function GetScheduleConfig() {
  return window['go']['main']['App']['GetScheduleConfig']();
}

export function GetSeason() {
  return window['go']['main']['App']['GetSeason']();
}

export function GetSeasonAnimes() {
  return window['go']['main']['App']['GetSeasonAnimes']();
}

export function GetSeasonMode() {
  return window['go']['main']['App']['GetSeasonMode']();
}

export function GetSeasonOrderingBoard() {
  return window['go']['main']['App']['GetSeasonOrderingBoard']();
}

export function GetSyncingAnimeItems() {
  return window['go']['main']['App']['GetSyncingAnimeItems']();
}

export function ImportSeasonIntake(arg1) {
  return window['go']['main']['App']['ImportSeasonIntake'](arg1);
}

export function ListDownloadRuns() {
  return window['go']['main']['App']['ListDownloadRuns']();
}

export function ListSeasons() {
  return window['go']['main']['App']['ListSeasons']();
}

export function OpenAnimeFolder(arg1) {
  return window['go']['main']['App']['OpenAnimeFolder'](arg1);
}

export function OpenAnimePage(arg1) {
  return window['go']['main']['App']['OpenAnimePage'](arg1);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function RecheckSeasonAvailability() {
  return window['go']['main']['App']['RecheckSeasonAvailability']();
}

export function ReconcileSeasonIntake(arg1) {
  return window['go']['main']['App']['ReconcileSeasonIntake'](arg1);
}

export function ReopenSeasonOrdering() {
  return window['go']['main']['App']['ReopenSeasonOrdering']();
}

export function RepeatAnime(arg1, arg2) {
  return window['go']['main']['App']['RepeatAnime'](arg1, arg2);
}

export function ResolveSeasonMatch(arg1, arg2) {
  return window['go']['main']['App']['ResolveSeasonMatch'](arg1, arg2);
}

export function RestoreAnime(arg1, arg2) {
  return window['go']['main']['App']['RestoreAnime'](arg1, arg2);
}

export function RunSeasonMatching() {
  return window['go']['main']['App']['RunSeasonMatching']();
}

export function SaveAnimeEditor(arg1) {
  return window['go']['main']['App']['SaveAnimeEditor'](arg1);
}

export function SaveSeasonOrderingDraft(arg1) {
  return window['go']['main']['App']['SaveSeasonOrderingDraft'](arg1);
}

export function SendSeasonAnimesToVerHoy(arg1) {
  return window['go']['main']['App']['SendSeasonAnimesToVerHoy'](arg1);
}

export function SetAnimeDays(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAnimeDays'](arg1, arg2, arg3);
}

export function SetAnimeState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAnimeState'](arg1, arg2, arg3);
}

export function SetDownloadsRoot(arg1) {
  return window['go']['main']['App']['SetDownloadsRoot'](arg1);
}

export function SetHosterPriority(arg1, arg2) {
  return window['go']['main']['App']['SetHosterPriority'](arg1, arg2);
}

export function SetJDConfig(arg1) {
  return window['go']['main']['App']['SetJDConfig'](arg1);
}

export function SetScheduleConfig(arg1) {
  return window['go']['main']['App']['SetScheduleConfig'](arg1);
}

export function SetSeasonConsideration(arg1, arg2) {
  return window['go']['main']['App']['SetSeasonConsideration'](arg1, arg2);
}

export function SetSeasonGrade(arg1, arg2) {
  return window['go']['main']['App']['SetSeasonGrade'](arg1, arg2);
}

export function SetSeasonMinApprovalGrade(arg1) {
  return window['go']['main']['App']['SetSeasonMinApprovalGrade'](arg1);
}

export function SetSeasonSlots(arg1) {
  return window['go']['main']['App']['SetSeasonSlots'](arg1);
}

export function SkipSeasonGrading(arg1) {
  return window['go']['main']['App']['SkipSeasonGrading'](arg1);
}

export function SoftDeleteAnime(arg1, arg2) {
  return window['go']['main']['App']['SoftDeleteAnime'](arg1, arg2);
}

export function TriggerAnimeDownload(arg1) {
  return window['go']['main']['App']['TriggerAnimeDownload'](arg1);
}

export function TriggerDownloadCheck() {
  return window['go']['main']['App']['TriggerDownloadCheck']();
}

export function TriggerReconcile() {
  return window['go']['main']['App']['TriggerReconcile']();
}

export function TriggerSeasonDownloads() {
  return window['go']['main']['App']['TriggerSeasonDownloads']();
}

export function UnpairDevice(arg1) {
  return window['go']['main']['App']['UnpairDevice'](arg1);
}
